[package]
name = "core"
version = "0.1.0"
authors = ["Artefact Inc. <admin@artefact.co.jp>"]

[dependencies]
actix = { branch = "master", git = "https://github.com/actix/actix.git" }
actix-web = { branch = "master", git = "https://github.com/actix/actix-web.git" }
base64 = "0.9.2"
chrono = { version = "0.4.0", features = ["serde"] }
diesel = { version = "1.3.2", features = ["postgres", "chrono", "r2d2", "uuid", "numeric"] }
failure = "0.1.1"
futures = "0.1"
jsonwebtoken = "4.0.1"
r2d2 = "0.8"
r2d2_redis = "0.7.0"
redis = "0.8.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
uuid = { version = "0.6", features = ["serde", "v4"] }

types = { path = "../types" }
